title: Python in the First Year Physics Lab Course
author: Freek Pols
logo: figures/TUDelft_logo_rgb.png #add your own logo here

execute:
  execute_notebooks: "auto"

only_build_toc_files: true

html:
  favicon : "figures/favicon.ico"
  baseurl :  "" #Replace this with your own URL

sphinx:
  config:
    nb_execution_includepatterns:
      - "Course files/Notebook 6/Notebook 6 Measurement uncertainty.ipynb"
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      repository_url: "https://github.com/jjhvandervliet/FYPLC" #add your own repo URL here
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
        thebe: true
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
  extra_extensions:
    - teachbooks_favourites
    - sphinx_tudelft_theme
    - sphinx_nb_execution_patterns


bibtex_bibfiles: 
  - references.bib
